# Generated by Django 5.0.4 on 2024-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='department',
            new_name='i1',
        ),
        migrations.RemoveField(
            model_name='react',
            name='employee',
        ),
        migrations.AddField(
            model_name='react',
            name='i2',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='i3',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='i4',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='i5',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
